CREATE DATABASE sistema_contas;

CREATE TABLE ENTRADAS (
ID_ENTRADA INT PRIMARY KEY AUTO_INCREMENT,
ORIGEM VARCHAR(100),
VALOR VARCHAR(12),
DIA_RECEBIMENTO VARCHAR(2),
ID_MES INT
)

CREATE TABLE DIVIDAS (
ID_DIVIDA INT PRIMARY KEY AUTO_INCREMENT,
ORIGEM VARCHAR(100),
DESCRICAO VARCHAR(100),
VALOR DOUBLE(12),
VENCIMENTO DATE,
ID_MES INT
)

CREATE TABLE MES (
ID_MES INT PRIMARY KEY AUTO_INCREMENT,
DESCRICAO VARCHAR(255)
)

-- CREATE TABLE Relacao1 (
-- ID_MES VARCHAR(10),
-- ID_ENTRADA VARCHAR(10),
-- FOREIGN KEY(ID_MES) REFERENCES MES (ID_MES),
-- FOREIGN KEY(ID_ENTRADA) REFERENCES ENTRADAS (ID_ENTRADA)
-- )

-- CREATE TABLE Relacao2 (
-- ID_MES VARCHAR(10),
-- ID_DIVIDA VARCHAR(10),
-- FOREIGN KEY(ID_MES) REFERENCES MES (ID_MES),
-- FOREIGN KEY(ID_DIVIDA) REFERENCES DIVIDAS (ID_DIVIDA)
-- )

ALTER TABLE ENTRADAS ADD CONSTRAINT FK_ID_MES
FOREIGN KEY(ID_MES) REFERENCES MES(ID_MES);

ALTER TABLE DIVIDAS ADD CONSTRAINT FK_ID_MES_DIVIDAS
FOREIGN KEY(ID_MES) REFERENCES MES(ID_MES);

INSERT INTO MES (DESCRICAO) VALUES ('JANEIRO');
INSERT INTO MES (DESCRICAO) VALUES ('FEVEREIRO');
INSERT INTO MES (DESCRICAO) VALUES ('MARÇO');
INSERT INTO MES (DESCRICAO) VALUES ('ABRIL');
INSERT INTO MES (DESCRICAO) VALUES ('MAIO');
INSERT INTO MES (DESCRICAO) VALUES ('JUNHO');
INSERT INTO MES (DESCRICAO) VALUES ('JULHO');
INSERT INTO MES (DESCRICAO) VALUES ('AGOSTO');
INSERT INTO MES (DESCRICAO) VALUES ('SETEMBRO');
INSERT INTO MES (DESCRICAO) VALUES ('OUTUBRO');
INSERT INTO MES (DESCRICAO) VALUES ('NOVEMBRO');
INSERT INTO MES (DESCRICAO) VALUES ('DEZEMBRO');